/*
 * Adapted from The MIT License (MIT)
 *
 * Copyright (c) 2020-2025 DaPorkchop_
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
 * is furnished to do so, subject to the following conditions:
 *
 * Any persons and/or organizations using this software must include the above copyright notice and this permission notice,
 * provide sufficient credit to the original authors of the project (IE: DaPorkchop_), as well as provide a link to the original project.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package net.daporkchop.fp2.gl.shader.source;

import lombok.Getter;
import lombok.NonNull;
import net.daporkchop.fp2.api.util.Identifier;
import net.daporkchop.fp2.common.util.ResourceProvider;
import net.daporkchop.fp2.common.util.exception.ResourceNotFoundException;
import net.daporkchop.fp2.gl.OpenGL;
import net.daporkchop.lib.common.annotation.param.Positive;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static net.daporkchop.lib.common.util.PValidation.*;

/**
 * Processes {@code #include} directives in a GLSL source file.
 *
 * @author DaPorkchop_
 */
public final class IncludePreprocessor {
    private static final Identifier HEADER_ID = Identifier.fromLenient("opengl", "<auto-generated-header>");
    private static final Identifier MACROS_ID = Identifier.fromLenient("opengl", "<auto-generated-macros>");
    private static final int HEADER_FILE_NUMBER = 0;
    private static final int MACROS_FILE_NUMBER = 1;

    private static final Pattern INCLUDE_PATTERN = Pattern.compile("^#include <\"([^\"]+)\">");

    private final @NonNull OpenGL gl;
    private final @NonNull ResourceProvider resourceProvider;
    private final int lineNumberOffset;

    private int macrosLineNumber = 1;

    @Getter
    private final StringBuilder buffer = new StringBuilder();
    @Getter
    private final List<Identifier> locations = new ArrayList<>();

    private final Set<Identifier> includedFilesWithPragmaOnce = Collections.newSetFromMap(new IdentityHashMap<>());

    public IncludePreprocessor(@NonNull OpenGL gl, @NonNull ResourceProvider resourceProvider) {
        this.gl = gl;
        this.resourceProvider = resourceProvider;
        this.lineNumberOffset = gl.version().glsl() >= 330 ? 0 : -1;

        this.locations.add(HEADER_ID);
        this.locations.add(MACROS_ID);
    }

    private IncludePreprocessor(IncludePreprocessor source) {
        this.gl = source.gl;
        this.resourceProvider = source.resourceProvider;
        this.lineNumberOffset = source.lineNumberOffset;
        this.macrosLineNumber = source.macrosLineNumber;

        this.buffer.append(source.buffer);
        this.locations.addAll(source.locations);
        this.includedFilesWithPragmaOnce.addAll(source.includedFilesWithPragmaOnce);
    }

    /**
     * @return a copy of this {@link IncludePreprocessor} in the same state
     */
    @Override
    public IncludePreprocessor clone() {
        return new IncludePreprocessor(this);
    }

    private void emitFileDirective(int fileNumber, @Positive int lineNumber) {
        this.buffer.append("#line ").append(lineNumber + this.lineNumberOffset).append(' ').append(fileNumber).append('\n');
    }

    private int assignFileNumber(Identifier file) {
        int fileNumber = this.locations.size();
        this.locations.add(file);
        return fileNumber;
    }

    /**
     * Adds the version string for the current OpenGL context to the beginning of the shader source code.
     */
    public IncludePreprocessor addVersionHeader() {
        checkState(this.buffer.length() == 0, "version header must be at top of shader source");

        //we don't need to emit a #file directive before this, since #version needs to be at the top
        this.buffer.append(this.gl.glslHeader());
        return this;
    }

    /**
     * Defines the given preprocessor macros.
     *
     * @param defines the names and values of the preprocessor macros to define
     */
    public IncludePreprocessor define(Map<String, ?> defines) {
        checkState(!this.locations.isEmpty(), "defines may not be at top of shader source");

        this.emitFileDirective(MACROS_FILE_NUMBER, this.macrosLineNumber);
        for (Map.Entry<String, ?> entry : defines.entrySet()) {
            Object rawValue = entry.getValue();
            String value;
            if (rawValue instanceof Boolean) {
                value = ((boolean) rawValue) ? "1" : "0";
            } else {
                value = String.valueOf(rawValue);
            }

            this.buffer.append("#define ").append(entry.getKey()).append(' ').append(value).append('\n');
            this.macrosLineNumber++;
        }
        return this;
    }

    /**
     * Includes the source lines from the file with the given {@link Identifier}.
     *
     * @param file the {@link Identifier} of the source file to be included
     */
    public IncludePreprocessor include(Identifier file) throws IOException, ResourceNotFoundException {
        if (this.includedFilesWithPragmaOnce.contains(file)) {
            //this source file contains a "#pragma once" and has already been included, don't include it again!
            //TODO: if the source file is included conditionally, we should probably include the file anyway
            return this;
        }

        int fileNumber = this.assignFileNumber(file);
        this.emitFileDirective(fileNumber, 1);

        int lineNo = 0;
        for (String line : this.resourceProvider.provideResourceAsLines(file)) {
            lineNo++;

            if (line.startsWith("#include ")) {
                Matcher matcher = INCLUDE_PATTERN.matcher(line);
                checkArg(matcher.find(), line);
                this.include(Identifier.from(matcher.group(1)));

                //emit another #file directive to switch back to the current file
                this.emitFileDirective(fileNumber, lineNo + 1);
            } else if ("#pragma once".equals(line)) {
                //remember that the file contained a line with "#pragma once" so that we don't end up including it again
                this.includedFilesWithPragmaOnce.add(file);
            } else {
                this.buffer.append(line).append('\n');
            }
        }
        return this;
    }
}
