/*
 * Adapted from The MIT License (MIT)
 *
 * Copyright (c) 2020-$today.year DaPorkchop_
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
 * is furnished to do so, subject to the following conditions:
 *
 * Any persons and/or organizations using this software must include the above copyright notice and this permission notice,
 * provide sufficient credit to the original authors of the project (IE: DaPorkchop_), as well as provide a link to the original project.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 */

//synced with net.daporkchop.fp2.core.client.render.compute.ComputeTextureMipmapGenerator#SHADER_WORK_GROUP_TILE_SIZE
layout(local_size_x = 16, local_size_y = 16) in;

//synced with net.daporkchop.fp2.core.client.render.compute.ComputeTextureMipmapGenerator#MAX_LEVELS_PER_DISPATCH
const uint MAX_LEVELS_PER_DISPATCH = 1u;

//
//
// MACROS
//
//

#ifndef FP2_MIPMAP_MODE
    #error "FP2_MIPMAP_MODE must be defined!"
#endif // FP2_MIPMAP_MODE

#ifndef FP2_MIPMAP_SRC_SAMPLER
    #error "FP2_MIPMAP_SRC_SAMPLER must be defined!"
#endif // FP2_MIPMAP_SRC_SAMPLER

#ifndef FP2_MIPMAP_FORMAT_IMAGE_LAYOUT
    #error "FP2_MIPMAP_FORMAT_IMAGE_LAYOUT must be defined!"
#endif // FP2_MIPMAP_FORMAT_IMAGE_LAYOUT

#ifndef FP2_MIPMAP_FORMAT_IMAGE_TYPE
    #error "FP2_MIPMAP_FORMAT_IMAGE_TYPE must be defined!"
#endif // FP2_MIPMAP_FORMAT_IMAGE_TYPE

#ifndef FP2_MIPMAP_FORMAT_SAMPLER_TYPE
    #error "FP2_MIPMAP_FORMAT_SAMPLER_TYPE must be defined!"
#endif // FP2_MIPMAP_FORMAT_SAMPLER_TYPE

#ifndef FP2_MIPMAP_FORMAT_RAW_TEXEL_TYPE
    #error "FP2_MIPMAP_FORMAT_RAW_TEXEL_TYPE must be defined!"
#endif // FP2_MIPMAP_FORMAT_RAW_TEXEL_TYPE

//synced with net.daporkchop.fp2.core.client.render.compute.ComputeTextureMipmapGenerator$MipmapMode
#define FP2_MIPMAP_MODE_MIN (0)
#define FP2_MIPMAP_MODE_MAX (1)

#if FP2_MIPMAP_MODE == FP2_MIPMAP_MODE_MIN
    #define mipmapReduce min
#elif FP2_MIPMAP_MODE == FP2_MIPMAP_MODE_MAX
    #define mipmapReduce max
#else
    #error "FP2_MIPMAP_MODE is set to an unsupported value!"
#endif

#define texel_t FP2_MIPMAP_FORMAT_RAW_TEXEL_TYPE

shared texel_t s_texelCache[gl_WorkGroupSize.x][gl_WorkGroupSize.y];

#if FP2_MIPMAP_SRC_SAMPLER
    uniform FP2_MIPMAP_FORMAT_SAMPLER_TYPE u_srcTexture;
    uniform int u_srcTextureLod;

    uvec2 srcLevelSize() {
        return uvec2(textureSize(u_srcTexture, u_srcTextureLod));
    }
#else
    uniform layout(FP2_MIPMAP_FORMAT_IMAGE_LAYOUT) restrict readonly FP2_MIPMAP_FORMAT_IMAGE_TYPE u_srcImage;

    uvec2 srcLevelSize() {
        return imageSize(u_srcImage);
    }
#endif

uniform layout(FP2_MIPMAP_FORMAT_IMAGE_LAYOUT) restrict writeonly FP2_MIPMAP_FORMAT_IMAGE_TYPE u_dstImage;

texel_t loadTexelSafe(uvec2 coord) {
    //ensure the coordinates are in bounds
    //  (this will result in the edge pixels being loaded multiple times, but it doesn't matter because the performance
    //  impact should be zero on modern GPU architectures and it won't affect the subsequent computations)
    coord = min(coord, srcLevelSize() - 1u);

    #if FP2_MIPMAP_SRC_SAMPLER
        return texelFetch(u_srcTexture, ivec2(coord), u_srcTextureLod);
    #else
        return imageLoad(u_srcImage, ivec2(coord));
    #endif
}

void main() {
    uvec2 dstTexelCoord = gl_WorkGroupID.xy * gl_WorkGroupSize.xy + gl_LocalInvocationID.xy;

    uvec2 srcLevelSize = srcLevelSize();
    uvec2 firstDstLevelSize = max(srcLevelSize / 2u, 1u);

    /*//load texels into the cache
    uvec2 srcTexelCoord = firstDstTexelCoord * 2u;
    s_texelCache[srcTexelCoord.x + 0u][srcTexelCoord.y + 0u] = loadTexelSafe(srcTexelCoord + uvec2(0u, 0u));
    s_texelCache[srcTexelCoord.x + 0u][srcTexelCoord.y + 1u] = loadTexelSafe(srcTexelCoord + uvec2(0u, 1u));
    s_texelCache[srcTexelCoord.x + 1u][srcTexelCoord.y + 0u] = loadTexelSafe(srcTexelCoord + uvec2(1u, 0u));
    s_texelCache[srcTexelCoord.x + 1u][srcTexelCoord.y + 1u] = loadTexelSafe(srcTexelCoord + uvec2(1u, 1u));*/

    if (any(greaterThanEqual(dstTexelCoord, firstDstLevelSize))) {
        //this sample is out-of-bounds in the destination level, skip it
        return;
    }

    //load texels
    uvec2 srcTexelCoord = dstTexelCoord * 2u;
    texel_t src00 = loadTexelSafe(srcTexelCoord + uvec2(0u, 0u));
    texel_t src01 = loadTexelSafe(srcTexelCoord + uvec2(0u, 1u));
    texel_t src10 = loadTexelSafe(srcTexelCoord + uvec2(1u, 0u));
    texel_t src11 = loadTexelSafe(srcTexelCoord + uvec2(1u, 1u));

    texel_t result = mipmapReduce(mipmapReduce(src00, src01), mipmapReduce(src10, src11));

    imageStore(u_dstImage, ivec2(dstTexelCoord), result);
}
