/*
 * Adapted from The MIT License (MIT)
 *
 * Copyright (c) 2020-$today.year DaPorkchop_
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
 * is furnished to do so, subject to the following conditions:
 *
 * Any persons and/or organizations using this software must include the above copyright notice and this permission notice,
 * provide sufficient credit to the original authors of the project (IE: DaPorkchop_), as well as provide a link to the original project.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 */

layout(local_size_x = 256) in;

#include <"fp2:shaders/common.glsl"> // T_SHIFT, T_VOXELS

#include <"fp2:shaders/util/frustum.glsl"> // isBoxInFrustum()
#include <"fp2:shaders/util/camera_state_uniforms.glsl"> // u_positionFrac, u_positionFloor
#include <"fp2:shaders/util/indirect_draw.glsl"> // DrawElementsIndirectCommand
#include <"fp2:shaders/util/vanilla_renderability.glsl"> // isVanillaRenderableLevel0()

#ifndef FP2_COUNT_SELECTED
    #error "FP2_COUNT_SELECTED must be set!"
#endif

#ifndef FP2_INDIRECT_COUNT
    #error "FP2_INDIRECT_COUNT must be set!"
#endif

#if !FP2_COUNT_SELECTED && FP2_INDIRECT_COUNT
    #error "FP2_INDIRECT_COUNT requires FP2_COUNT_SELECTED!"
#endif

layout(std140) readonly restrict buffer B_TilePositions {
    ivec4 b_tilePositions[];
};

layout(std430) readonly restrict buffer B_RawDrawLists {
    DrawElementsIndirectCommand b_rawDrawLists[];
};

layout(std430) writeonly restrict buffer B_CulledDrawLists {
    DrawElementsIndirectCommand b_culledDrawLists[];
};

#if FP2_COUNT_SELECTED
    layout(binding = COUNT_SELECTED_COUNTER_BINDING) uniform atomic_uint ac_selectedTileCount;
    layout(binding = COUNT_SELECTED_COUNTER_BINDING) uniform atomic_uint ac_selectedCommandCounts[RENDER_PASS_COUNT];
#endif

bool select(uint tileIndex) {
    ivec4 pos = b_tilePositions[tileIndex];

    // If the tile's level is negative, it indicates that the tile doesn't exist and can definitely be skipped
    if (pos.w < 0) {
        return false;
    }

    // Level-0 tiles must not overlap vanilla renderable terrain
    if (pos.w == 0 && isVanillaRenderableLevel0(pos.xyz)) {
        return false;
    }

    ivec3 position_absolute = pos.xyz << (T_SHIFT + pos.w);
    ivec3 position_relative = position_absolute - u_positionFloor;

    return isBoxInFrustum(
            vec3(position_relative) - u_positionFrac,
            vec3(position_relative + ivec3((T_VOXELS + 1) << pos.w)) - u_positionFrac);
}

void main() {
    uint srcCommandIndex = gl_WorkGroupID.x * (gl_WorkGroupSize.x * gl_WorkGroupSize.y * gl_WorkGroupSize.z) + gl_LocalInvocationIndex;
    uint stride = gl_NumWorkGroups.x * (gl_WorkGroupSize.x * gl_WorkGroupSize.y * gl_WorkGroupSize.z);

    bool selected = select(srcCommandIndex);

    #if FP2_COUNT_SELECTED
        //if selected tile counting is enabled and this tile was selected, increment the selected tile count
        if (selected) {
            atomicCounterIncrement(ac_selectedTileCount);
        }
    #endif

    #if FP2_INDIRECT_COUNT
        //if we're rendering using MultiDraw with an indirect count and this tile was selected, copy the commands
        //  to the culled list while skipping empty ones. this will result in the commands for selected tiles being
        //  tightly packed at the front of the list, and unselected tiles will be skipped entirely.
        if (selected) {
            for (uint pass = 0u, commandIndexBase = 0u; pass < RENDER_PASS_COUNT; pass++, commandIndexBase += stride) {
                DrawElementsIndirectCommand srcCommand = b_rawDrawLists[commandIndexBase + srcCommandIndex];

                //if the command at this render pass is empty, skip it
                if (srcCommand.count == 0u) {
                    continue;
                }

                //determine which index the command should go at.
                //  pass is a dynamically uniform variable, so we can safely index the atomic counter array with it
                uint dstCommandIndex = atomicCounterIncrement(ac_selectedCommandCounts[pass]);

                //copy the command to the corresponding destination slot
                b_culledDrawLists[commandIndexBase + dstCommandIndex] = srcCommand;
            }
        }
    #else
        //if we're rendering using conventional indirect MultiDraw, copy the command list as-is but replace commands
        //  with an empty command if this tile isn't selected, so that rendering the commands becomes a no-op.
        for (uint pass = 0u, commandIndex = srcCommandIndex; pass < RENDER_PASS_COUNT; pass++, commandIndex += stride) {
            DrawElementsIndirectCommand srcCommand = b_rawDrawLists[commandIndex];

            #if FP2_COUNT_SELECTED
                //if we're rendering using conventional indirect MultiDraw, but selected command counting is still enabled,
                //  we need to increment the counters.
                if (selected && srcCommand.count != 0u) {
                    //pass is a dynamically uniform variable, so we can safely index the atomic counter array with it
                    atomicCounterIncrement(ac_selectedCommandCounts[pass]);
                }
            #endif

            b_culledDrawLists[commandIndex] = selected ? srcCommand : DrawElementsIndirectCommand(0, 0, 0, 0, 0);
        }
    #endif
}
