# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# Check these at https://fabricmc.net/develop/
minecraft_version=26.1.2
loader_version=0.19.3

# Mod Properties
mod_version=0.1.0
maven_group=dev.farplane
archives_base_name=farplane

# Dependencies
loom_version=1.17-SNAPSHOT
fabric_api_version=0.155.2+26.1.2
